// Як працює try catch ?

// Припустимо ми хотіли б вивести у консоль змінну test, але ми її ніде не оголошували:

// console.log(test); // відповідно у нас виникне помилка

// далі по коду ми хотіли б доприкладу ще щось викликати, припустимо змінну:
// const work = 'Працює'; 
// console.log(work);
// Але виникне помилка, тому що на попередньому етапі ми намагалися викликати змінну test

// Саме try catch дає можливість якісь часточки коду обробляти безпечно, а саме:
// ми можемо огорнути наш console.log(test); в конструкцію try catch, де якщо виникне помилка в try, то в catch
// покаже де була помилка:

try {
    console.log(test);
} catch (error) {
    console.log(error);
}
console.log(work);

// Тепер ми можемо бачити що та ж сама помилка з'явиться у консолі, але код піде далі і покаже нам результат значення
// змінної console.log(work);

// Краже всього використовувати дану конструкцію коли ми хотіли б отримати інформацію, але ми не знаємо чи вона там є.
// Використовуеться з асинхронним js

// Насправді працює три параметра:

// try {
//     console.log(test);
// } catch (error) {
//     console.log(error);
// } finally

// де:
// try - спробуй щось зробити (отримати елемент з локал сторедж або выдповідь з сервера)
// catch - відлови мені помилку якщо якась виникла
// finally - виконається завжди але після двох попередніх